### ISSUE TITLE
'<' not supported between instances of 'functools.partial' and 'int'

### ISSUE THREAD

**Issue by jingweitan** [bwconrad/flexivit#6]
Hi, thanks for reproducing this in pytorch version.
I am trying to buikd the model as suggested but I encountered a bug and I'm not sure how to solve. 
When I run  **enc = flexivit_base()** , it provided me this bug 
![image](https://github.com/bwconrad/flexivit/assets/48575204/3ef6da0c-8177-42eb-b2c4-89ccfe7bb66e)

Could you help me to check on this?
Thanks in advance!

**Comment by Arwa-AlRubaian** [comment]
Hello, 
@jingweitan  did you figure out how to solve the error ? 
I am experiencing the same issue, if you could kindly assist .. 
Thanks !
